### ISSUE TITLE
非常好！！界面可以在优化一下

### ISSUE THREAD

**Issue by iHTCboy** [AsTryE/xTransCodelation#7]
如标题。支持！！！申请有道key时，名字只能是英文，而且随便写，点击申请就通过了。这个bug可以告诉大家啊！

**Comment by AsTryE** [comment]
优化网页布局方式，不再采取SDK方式了，更简单。

**Comment by iHTCboy** [comment]
非常好，以后看文档轻松了，谢谢，支持，继续更新！美化！
