### ISSUE TITLE
能否增加段落翻译，现在最多只能翻译一行的英文

### ISSUE THREAD

**Issue by heartjoy** [AsTryE/xTransCodelation#8]
能否增加段落翻译，现在最多只能翻译一行的英文

**Comment by AsTryE** [comment]
其实能翻译多少文字是有道词典那面的限制。我试了下，可以翻译多行的，一种使用方式是：双击某个单词后默认就会选中该单词然后弹出“译”的图标；第二种：你可以按住鼠标左键的同时拖动选中多行内容，点击出现的“译”，这也是可以的，希望能帮到你。
